deploy: fix PR #20
PR #20 introduced broken .yaml, causing a failure from kubectl:
   error: error parsing STDIN: error converting YAML to JSON: yaml: line 91: did not find expected key